
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Disciplanner.Resources
{

    using System;
    using System.Collections.Generic;

    public class Appointment
    {
        TimeUtil time = new TimeUtil();
        public Appointment(string Name, string Category, string Notes, int Priority, string StartTime = "undefined", string EndTime = "undefined", int ParentEntity = -1)
        {
            this.Name = Name;
            this.CreationTime = time.getCurrentTime();
            this.Category = Category;
            this.Notes = Notes;
            this.Priority = Priority;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
            this.ParentEntity = ParentEntity;
        }
        public int AppointmentID { get; }

        public string Name { get; set; }

        public string CreationTime { get; }

        public string Category { get; set; }

        public string Notes { get; set; }

        public int Priority { get; set; }

        public string StartTime { get; set; }

        public string EndTime { get; set; }

        public int ParentEntity { get; set; }

    }

}
