//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disciplanner.Resources
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deadline
    {
        public int DeadlineID { get; set; }
        public string Name { get; set; }
        public string CreationTime { get; set; }
        public string Category { get; set; }
        public string Notes { get; set; }
        public int Priority { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int ParentEntity { get; set; }
    }
}
